name: Pull Request Quality Gate

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  quality_gate:
    runs-on: ubuntu-latest

    steps:
    - name: Check for allow_pull_request.txt
      run: |
        if [ -f "allow_pull_request.txt" ]; then
          echo "Permitiendo Pull Request"
        else
          echo "Impidiendo Pull Request"
          exit 1
        fi
