name: Continuous Integration

on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'hotfix/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run SAST tests
      run: echo "Running SAST tests"

    - name: Create credentials.ini
      run: echo -e "[auth]\nusername=${{ secrets.USERNAME }}\npassword=${{ secrets.PASSWORD }}" > credentials.ini

    - name: Build Docker image
      run: docker build -t devops_ws . --tag devops_ws_$(date +\%s)
